### ISSUE TITLE
Schedule Out of Date

### ISSUE THREAD

**Issue by taarmstr** [Bekt/uark-schedule-watcher#3]
Hi, the schedule lists needs to be updated for Fall 2016 courses. I really appreciate this website and it is very convenient besides the fact that it does not automatically update.

**Comment by Bekt** [comment]
Hey @taarmstr! 

Thanks for using this and reporting, I've updated the list: http://watcher.bekt.net/

I've heard some people were getting the emails in the 'Spam' folder, so look out for that.

I'll look into auto-updating the list regularly if I have some free time.
